version: '3.8'
services:
  web-config:
    container_name: web-config
    build: .
    network_mode: host
    privileged: true 
    stdin_open: true  # Equivalent to -i
    tty: true  # Equivalent to -t
